server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      database: reactivedb
  jackson:
      serialization:
          indent_output: true
          write_dates_as_timestamps: false
          write_durations_as_timestamps: false
logging:
  level:
    org.springframework.web: DEBUG